import { randomBytes, createHash } from "node:crypto";
import { constants } from "node:fs";
import { access, mkdir, rm, stat } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import type { ImageConfig, StringMap } from "./types.js";

export class NodeVmmError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "NodeVmmError";
  }
}

export function randomId(prefix = "vm"): string {
  return `${prefix}-${randomBytes(4).toString("hex")}`;
}

export async function pathExists(target: string): Promise<boolean> {
  try {
    await access(target, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

export function absolutePath(target: string): string {
  return path.resolve(process.cwd(), target);
}

export async function makeTempDir(prefix = "node-vmm-"): Promise<string> {
  const dir = path.join(os.tmpdir(), `${prefix}${randomBytes(4).toString("hex")}`);
  await mkdir(dir, { recursive: true, mode: 0o700 });
  return dir;
}

export async function makeTempDirIn(parent: string, prefix = "node-vmm-"): Promise<string> {
  const dir = path.join(parent, `${prefix}${randomBytes(4).toString("hex")}`);
  await mkdir(dir, { recursive: true, mode: 0o700 });
  return dir;
}

export async function isWritableDirectory(target: string): Promise<boolean> {
  try {
    const info = await stat(target);
    if (!info.isDirectory()) {
      return false;
    }
    await access(target, constants.W_OK);
    return true;
  } catch {
    return false;
  }
}

export async function removePath(target: string): Promise<void> {
  await rm(target, { recursive: true, force: true });
}

export function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export function requireRoot(action: string): void {
  if (typeof process.getuid === "function" && process.getuid() !== 0) {
    throw new NodeVmmError(`${action} requires root privileges. Re-run with sudo.`);
  }
}

export function shellQuote(value: string): string {
  if (value.length === 0) {
    return "''";
  }
  return `'${value.replaceAll("'", "'\\''")}'`;
}

export function quoteArgv(argv: string[]): string {
  return argv.map(shellQuote).join(" ");
}

export function parseKeyValueList(values: string[]): StringMap {
  const out: StringMap = {};
  for (const raw of values) {
    const pieces = raw
      .split(",")
      .map((piece) => piece.trim())
      .filter(Boolean);
    for (const piece of pieces) {
      const index = piece.indexOf("=");
      if (index <= 0) {
        throw new NodeVmmError(`expected KEY=VALUE, got ${piece}`);
      }
      const key = piece.slice(0, index);
      const value = piece.slice(index + 1);
      if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) {
        throw new NodeVmmError(`invalid environment/build argument name: ${key}`);
      }
      out[key] = value;
    }
  }
  return out;
}

export function imageEnvToMap(env: string[]): StringMap {
  const out: StringMap = {};
  for (const item of env) {
    const index = item.indexOf("=");
    if (index > 0) {
      out[item.slice(0, index)] = item.slice(index + 1);
    }
  }
  return out;
}

export function renderEnvFile(env: StringMap): string {
  const lines = ["# Generated by node-vmm."];
  for (const [key, value] of Object.entries(env).sort(([a], [b]) => a.localeCompare(b))) {
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) {
      continue;
    }
    lines.push(`export ${key}=${shellQuote(value)}`);
  }
  return `${lines.join("\n")}\n`;
}

export function commandLineFromImage(
  imageConfig: ImageConfig,
  override: { cmd?: string; entrypoint?: string },
): string {
  if (override.cmd && override.entrypoint) {
    return `${override.entrypoint} ${override.cmd}`.trim();
  }
  if (override.cmd) {
    const entrypoint = imageConfig.entrypoint.length > 0 ? quoteArgv(imageConfig.entrypoint) : "";
    return `${entrypoint} ${override.cmd}`.trim();
  }
  if (override.entrypoint) {
    const tail = imageConfig.cmd.length > 0 ? ` ${quoteArgv(imageConfig.cmd)}` : "";
    return `${override.entrypoint}${tail}`.trim();
  }
  const argv = [...imageConfig.entrypoint, ...imageConfig.cmd];
  if (argv.length > 0) {
    return quoteArgv(argv);
  }
  return "/bin/sh";
}

export function workdirFromImage(imageConfig: ImageConfig, override?: string): string {
  const selected = override || imageConfig.workingDir || "/";
  return selected.startsWith("/") ? selected : `/${selected}`;
}

export function deterministicMac(seed: string): string {
  const hash = createHash("sha256").update(seed).digest();
  return ["06", hash[0], hash[1], hash[2], hash[3], hash[4]]
    .map((part) => (typeof part === "string" ? part : part.toString(16).padStart(2, "0")))
    .join(":");
}

export function compactIdForTap(id: string): string {
  const cleaned = id.replace(/[^A-Za-z0-9]/g, "").slice(0, 10);
  return `jc${cleaned || randomBytes(4).toString("hex")}`.slice(0, 15);
}
